name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use oxr463/setup-leiningen
      uses: oxr463/setup-leiningen@0.0.1
      with:
        exec: |
          lein deps &&
          lein cljfmt check &&
          lein test
