name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - name: test
        uses: oxr463/setup-leiningen@0.0.1
        with:
          exec: |
            PATH=$PATH:$JAVA_HOME/bin
            echo $JAVA_HOME
            echo $PATH
            ls /opt/hostedtoolcache/Java_Zulu_jdk/21.0.6-7/x64
            lein deps &&
            lein cljfmt check &&
            lein test
