name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - name: debug java install
        run:
          echo $JAVA_HOME
          echo $PATH
          java -version
      # - name: test
      #   uses: oxr463/setup-leiningen@0.0.1
      #   with:
      #     exec: |
      #       PATH=$PATH:$JAVA_HOME/bin
      #       lein deps &&
      #       lein cljfmt check &&
      #       lein test
